### ISSUE TITLE
fix(scatterplot): address an issue where the Sonification autoplay does not work

### ISSUE THREAD

**Issue by jooyoungseo** [xability/py_maidr#69]
## Reproducible Steps

1. Download the required csv dataset from here: https://github.com/xability/a11y_ds_course/blob/main/data/gapminder.csv

1. Execute the following code within Python repl:

```python
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import maidr

gapminder = pd.read_csv('gapminder.csv')

# Scatter Plot of GDP per capita vs population
plt.figure(figsize=(10, 6))
gdp_pop_plot = sns.scatterplot(data=gapminder, x="pop", y="gdpPercap", hue="continent")
plt.title("GDP per Capita vs Population by Continent")
plt.xlabel("Population")
plt.ylabel("GDP per Capita")
plt.show()
maidr.show(gdp_pop_plot)
```

1. Tab to focus in the interactive maidr plot area.

1. Use autoplay (Ctrl+Shift+RightArrow) and see if that works.

## Current Behavior

Autoplay does not work.

**Comment by SaaiVenkat** [comment]
Professor @jooyoungseo , this is issue in the upstream. Looking into the issue.

**Comment by SaaiVenkat** [comment]
### Preliminary Investigation

We render the highlighting and the sonification using events with a specific timeout calculated based on the range of values. Since the datapoints are so close, but with high outliers, the timeout for highlighting is much smaller than the timeout for sonification (which is a constant 50ms). This causes only the highlighting events to be emitted. 

Moving to the upstream repository - https://github.com/xability/maidr/issues/519
