### ISSUE TITLE
feat: pick up matplotlib fmt towards maidr

### ISSUE THREAD

**Issue by jooyoungseo** [xability/py_maidr#77]
Currently, only raw data is stored in the maidr JSON schema.

If x and y axes are formatted via seaborn or matplotlib, the formatted values need to be parsed and applied to maidr.

**Comment by SaaiVenkat** [comment]
Professsor @jooyoungseo , could you please attach any examples?

**Comment by jooyoungseo** [comment]
@krperry -- Could you please share your reproducible code here?

**Comment by krperry** [comment]
You can get it from the course file if you need a clean copy but I will paste it here.  I have commented out the line where I round the column so you can see what seaborn is doing and what maidr is reading.  When I look at this graph with AI  Picture smart in Jaws.  All the values have 2 digits after the decimal point.  I assume that means what seaborn is showing is 2 digits after the point of course AI could be doing something.   What maidr reads though is the whole number.  If you look at the seaborn plot option I have fmt set for 2 digits.  Here is the code:

 

import seaborn as sns

import matplotlib.pyplot as plt

import maidr

 

tips = sns.load_dataset("tips")

 

# Pivot the data to have days as rows and time (meal) as columns

tips_pivot = tips.pivot_table(values='tip', index='day', columns='time', aggfunc='mean')

 

# get rid of the extra digits  (Ask Jooyoung about this. maybe maidr is speaking them.

#tips_pivot = tips_pivot.transform(lambda x: round( x,2))

 

#Change the Na to 0 because 0 sounds better and na affects maidr

tips_pivot = tips_pivot.fillna(0)

 

plt.figure(figsize=(10, 8))

tips = sns.heatmap(

data= tips_pivot,

annot=True,

fmt=".2f",

cmap="YlGnBu"

)

 

# Set the title

plt.title("Meal  tip amount for the week")

#plt.show()

maidr.show(tips)
