### ISSUE TITLE
ci(commitlint): address an issue where commitlint keeps failing

### ISSUE THREAD

**Issue by jooyoungseo** [xability/py_maidr#91]
Our commitlint keeps failing and we need to fix the CI.

**Comment by krishnanand5** [comment]
**Root cause Analysis:**

We are trying to execute the linter as an ES module whilst the file contains vanilla javascript. In order to sync the workflow with what we have the linter config, we need to install conventional commit dependancy via NPM through the job and convert the config file format from js to cjs.

This will resolve the ambiguity and allow the job to utilize the commitlint config file for the lint check.

**Comment by jooyoungseo** [comment]
Closed via #92
